/* Telegram kanal uchun viktorina savollari (Telegram "Quiz" so'rovnomasi).
   Har kuni 3 ta: 1) lug'at, 2) grammatika/harf, 3) qiziqarli viktorina.

   Cheklovlar (Telegram): savol ≤ 300 belgi, variant ≤ 100 belgi,
   izoh ≤ 200 belgi, 2–10 variant. `correct` — to'g'ri variant indeksi (0 dan).
   Qoidalar: diniy mavzu yo'q, narx yo'q, faktlar tekshirilgan.

   Yangi hafta qo'shish: shu ro'yxatga w2… id bilan qo'shiladi YOKI
   ERP → Telegram bot → Viktorina → «Savollarni qo'shish» orqali.      */
'use strict';

module.exports = [
  /* ---------- 1-hafta ---------- */
  { id: 'w1d1s1', kind: 'Lug‘at', question: '📚 «كِتَاب» (kitāb) so‘zi nimani bildiradi?',
    options: ['Daftar', 'Kitob', 'Qalam', 'Stol'], correct: 1,
    explain: 'كِتَاب — kitob. Ko‘pligi: كُتُب (kutub). O‘zbekchadagi «kitob» so‘zi ham shundan.' },
  { id: 'w1d1s2', kind: 'Alifbo', question: '🔤 Arab alifbosida nechta harf bor?',
    options: ['24', '26', '28', '32'], correct: 2,
    explain: 'Arab alifbosida 28 ta harf bor. Ko‘p harflar so‘z ichida shaklini o‘zgartiradi.' },
  { id: 'w1d1s3', kind: 'Viktorina', question: '🧭 Arab tilida yozuv qaysi yo‘nalishda yoziladi?',
    options: ['Chapdan o‘ngga', 'O‘ngdan chapga', 'Yuqoridan pastga', 'Ikkala tomonga'], correct: 1,
    explain: 'Arabcha o‘ngdan chapga yoziladi, lekin raqamlar chapdan o‘ngga o‘qiladi.' },

  { id: 'w1d2s1', kind: 'Lug‘at', question: '💬 «شُكْرًا» (shukran) nima degani?',
    options: ['Kechirasiz', 'Rahmat', 'Xayr', 'Marhamat'], correct: 1,
    explain: 'شُكْرًا — rahmat. Javobiga «عَفْوًا» (‘afwan) — arzimaydi, deyiladi.' },
  { id: 'w1d2s2', kind: 'Alifbo', question: '🔤 «ب» harfi qanday o‘qiladi?',
    options: ['T', 'B', 'N', 'Y'], correct: 1,
    explain: 'ب — «bā», B tovushi. Ostidagi bitta nuqtasi bilan ت (T) va ث (S) dan farq qiladi.' },
  { id: 'w1d2s3', kind: 'Viktorina', question: '🌍 Arab tili BMTning rasmiy tillaridan biri. BMTda jami nechta rasmiy til bor?',
    options: ['4 ta', '6 ta', '8 ta', '10 ta'], correct: 1,
    explain: 'BMTning 6 ta rasmiy tili: arab, ingliz, xitoy, fransuz, rus va ispan.' },

  { id: 'w1d3s1', kind: 'Lug‘at', question: '🏠 «بَيْت» (bayt) so‘zining ma’nosi?',
    options: ['Uy', 'Eshik', 'Ko‘cha', 'Bog‘'], correct: 0,
    explain: 'بَيْت — uy. «Eshik» arabchada بَاب (bāb).' },
  { id: 'w1d3s2', kind: 'Grammatika', question: '👤 «أَنَا» (ana) olmoshi qaysi so‘zga to‘g‘ri keladi?',
    options: ['Sen', 'U', 'Men', 'Biz'], correct: 2,
    explain: 'أَنَا — men. Biz — نَحْنُ (nahnu), u (erkak) — هُوَ (huwa).' },
  { id: 'w1d3s3', kind: 'Viktorina', question: '🇺🇿 Quyidagi o‘zbekcha so‘zlardan qaysi biri arab tilidan kirgan?',
    options: ['Non', 'Kitob', 'Tosh', 'Suv'], correct: 1,
    explain: '«Kitob» arabcha كِتَاب dan. «Tosh» va «suv» — turkiy, «non» — forscha so‘z.' },

  { id: 'w1d4s1', kind: 'Lug‘at', question: '💧 «مَاء» (mā’) nima degani?',
    options: ['Suv', 'Non', 'Choy', 'Sut'], correct: 0,
    explain: 'مَاء — suv. Sut — حَلِيب (halīb), non — خُبْز (xubz).' },
  { id: 'w1d4s2', kind: 'Lug‘at', question: '📏 Arabchada «katta» qaysi so‘z?',
    options: ['صَغِير', 'كَبِير', 'جَدِيد', 'قَدِيم'], correct: 1,
    explain: 'كَبِير (kabīr) — katta. صَغِير — kichik, جَدِيد — yangi, قَدِيم — eski.' },
  { id: 'w1d4s3', kind: 'Viktorina', question: '📅 Xalqaro Arab tili kuni qachon nishonlanadi?',
    options: ['21-fevral', '18-dekabr', '1-sentabr', '8-mart'], correct: 1,
    explain: '18-dekabr — 1973-yilda shu kuni arab tili BMTning rasmiy tillari qatoriga qo‘shilgan.' },

  { id: 'w1d5s1', kind: 'Lug‘at', question: '✏️ «قَلَم» (qalam) so‘zining ma’nosi?',
    options: ['Qalam', 'Kitob', 'Daftar', 'Sumka'], correct: 0,
    explain: 'قَلَم — qalam. Daftar — دَفْتَر (daftar), sumka — حَقِيبَة (haqība).' },
  { id: 'w1d5s2', kind: 'Grammatika', question: '👨 Erkakka «sen» deyish uchun qaysi olmosh ishlatiladi?',
    options: ['أَنْتَ', 'أَنْتِ', 'هُوَ', 'نَحْنُ'], correct: 0,
    explain: 'أَنْتَ (anta) — erkakka «sen», أَنْتِ (anti) — ayolga «sen». Farq oxiridagi harakatda.' },
  { id: 'w1d5s3', kind: 'Viktorina', question: '🔢 Qaysi raqamlar dunyoda «arab raqamlari» deb ataladi?',
    options: ['I, V, X', '1, 2, 3', 'α, β, γ', '一, 二, 三'], correct: 1,
    explain: '1, 2, 3… Yevropaga arablar orqali o‘tgani uchun shunday ataladi; ularning asli Hindistondan.' },

  { id: 'w1d6s1', kind: 'Ibora', question: '🌅 «صَبَاحُ الْخَيْر» (sabāhu-l-xayr) nima degani?',
    options: ['Xayrli tun', 'Xayrli tong', 'Xush kelibsiz', 'Ishlar qalay?'], correct: 1,
    explain: 'صَبَاحُ الْخَيْر — xayrli tong. Javobi: صَبَاحُ النُّور (sabāhu-n-nūr).' },
  { id: 'w1d6s2', kind: 'Raqamlar', question: '🔢 «وَاحِد، اِثْنَان، ثَلَاثَة» — bu so‘zlar nima?',
    options: ['Ranglar', '1, 2, 3 raqamlari', 'Hafta kunlari', 'Oila a’zolari'], correct: 1,
    explain: 'وَاحِد — bir, اِثْنَان — ikki, ثَلَاثَة — uch.' },
  { id: 'w1d6s3', kind: 'Viktorina', question: '🌐 Arab tili nechta davlatda rasmiy til hisoblanadi?',
    options: ['5 ta', '10 ta', '20 dan ortiq', '50 dan ortiq'], correct: 2,
    explain: 'Arab tili 20 dan ortiq davlatda rasmiy til — Marokashdan Iroqqacha.' },

  { id: 'w1d7s1', kind: 'Lug‘at', question: '🚗 «سَيَّارَة» (sayyāra) so‘zining ma’nosi?',
    options: ['Mashina', 'Samolyot', 'Poyezd', 'Velosiped'], correct: 0,
    explain: 'سَيَّارَة — mashina. Samolyot — طَائِرَة (tā’ira), poyezd — قِطَار (qitār).' },
  { id: 'w1d7s2', kind: 'Grammatika', question: '✍️ So‘z oxiridagi «ة» (ta marbuta) ko‘pincha nimani bildiradi?',
    options: ['Ko‘plikni', 'Muannas (ayol jinsi)ni', 'O‘tgan zamonni', 'Savolni'], correct: 1,
    explain: 'ة ko‘pincha muannas belgisi: مُعَلِّم — ustoz (erkak), مُعَلِّمَة — ustoz (ayol).' },
  { id: 'w1d7s3', kind: 'Viktorina', question: '🧮 «Algebra» so‘zi qaysi vatandoshimiz kitobi nomidan kelib chiqqan?',
    options: ['Ibn Sino', 'Al-Xorazmiy', 'Beruniy', 'Ulug‘bek'], correct: 1,
    explain: 'Al-Xorazmiyning «Al-jabr val-muqobala» asari nomidagi «al-jabr» — algebra.' },
  /* ---------- 2-hafta ---------- */
  { id: 'w2d1s1', kind: 'Lug‘at', question: '🚪 «بَاب» (bāb) so‘zining ma’nosi?',
    options: ['Deraza', 'Eshik', 'Devor', 'Tom'], correct: 1,
    explain: 'بَاب — eshik. Deraza — نَافِذَة (nāfiza).' },
  { id: 'w2d1s2', kind: 'Alifbo', question: '🔤 «ت» harfi qanday o‘qiladi?',
    options: ['B', 'T', 'S', 'N'], correct: 1,
    explain: 'ت — «tā», T tovushi. Ustida ikki nuqta bor.' },
  { id: 'w2d1s3', kind: 'Viktorina', question: '🎵 Arab tilida nechta qisqa unli belgisi (harakat) bor?',
    options: ['2 ta', '3 ta', '5 ta', '6 ta'], correct: 1,
    explain: 'Uchta: fatha (a), kasra (i), damma (u). Ular harf ustiga yoki ostiga qo‘yiladi.' },

  { id: 'w2d2s1', kind: 'Lug‘at', question: '☀️ «شَمْس» (shams) nima degani?',
    options: ['Oy', 'Yulduz', 'Quyosh', 'Osmon'], correct: 2,
    explain: 'شَمْس — quyosh. Oy — قَمَر (qamar).' },
  { id: 'w2d2s2', kind: 'Grammatika', question: '👨 «هُوَ» (huwa) olmoshi kimni bildiradi?',
    options: ['Men', 'Sen', 'U (erkak)', 'U (ayol)'], correct: 2,
    explain: 'هُوَ — u (erkak), هِيَ (hiya) — u (ayol).' },
  { id: 'w2d2s3', kind: 'Grammatika', question: '📌 So‘z oldidagi «الـ» (al-) nimani bildiradi?',
    options: ['Ko‘plikni', 'Aniqlikni (inglizcha «the»)', 'Inkorni', 'Savolni'], correct: 1,
    explain: 'الـ — aniqlik artikli: كِتَاب — bir kitob, الْكِتَاب — o‘sha (aniq) kitob.' },

  { id: 'w2d3s1', kind: 'Lug‘at', question: '🌙 «قَمَر» (qamar) so‘zining ma’nosi?',
    options: ['Oy', 'Quyosh', 'Bulut', 'Yomg‘ir'], correct: 0,
    explain: 'قَمَر — oy (osmondagi). Yulduz — نَجْم (najm).' },
  { id: 'w2d3s2', kind: 'Grammatika', question: '👩 «هِيَ» (hiya) olmoshi kimni bildiradi?',
    options: ['U (ayol)', 'U (erkak)', 'Biz', 'Siz'], correct: 0,
    explain: 'هِيَ — u (ayol). Arab tilida «u» erkak va ayol uchun alohida.' },
  { id: 'w2d3s3', kind: 'Viktorina', question: '🏙 Misrning poytaxti qaysi shahar?',
    options: ['Qohira', 'Dubay', 'Bag‘dod', 'Ammon'], correct: 0,
    explain: 'Qohira — arabcha «الْقَاهِرَة» (al-Qāhira). Arab dunyosining eng katta shaharlaridan biri.' },

  { id: 'w2d4s1', kind: 'Lug‘at', question: '👩‍👧 «أُمّ» (umm) so‘zining ma’nosi?',
    options: ['Ota', 'Ona', 'Opa', 'Buvi'], correct: 1,
    explain: 'أُمّ — ona, أَب (ab) — ota.' },
  { id: 'w2d4s2', kind: 'Ibora', question: '👋 «مَعَ السَّلَامَة» (ma‘a-s-salāma) qachon aytiladi?',
    options: ['Salomlashganda', 'Xayrlashganda', 'Rahmat aytganda', 'Kechirim so‘raganda'], correct: 1,
    explain: 'مَعَ السَّلَامَة — «xayr, sog‘-salomat bo‘ling», xayrlashganda aytiladi.' },
  { id: 'w2d4s3', kind: 'Viktorina', question: '☕ «Kofe» so‘zi qaysi arabcha so‘zdan kelib chiqqan?',
    options: ['قَهْوَة (qahwa)', 'شَاي (shāy)', 'حَلِيب (halīb)', 'مَاء (mā’)'], correct: 0,
    explain: 'قَهْوَة → turkcha «kahve» → Yevropa tillarida «coffee», «kofe».' },

  { id: 'w2d5s1', kind: 'Lug‘at', question: '👨‍👦 «أَب» (ab) so‘zining ma’nosi?',
    options: ['Aka', 'Bobo', 'Ota', 'Amaki'], correct: 2,
    explain: 'أَب — ota. «Otam» — أَبِي (abī).' },
  { id: 'w2d5s2', kind: 'Ibora', question: '💬 «كَيْفَ حَالُكَ؟» (kayfa hāluka) nima degani?',
    options: ['Ismingiz nima?', 'Ahvolingiz qanday?', 'Qayerdansiz?', 'Necha yoshdasiz?'], correct: 1,
    explain: 'كَيْفَ حَالُكَ؟ — ahvolingiz qanday? Javob: بِخَيْر (bi-xayr) — yaxshi.' },
  { id: 'w2d5s3', kind: 'Viktorina', question: '📖 Mashhur «Ming bir kecha» ertaklari arabcha qanday ataladi?',
    options: ['أَلْف لَيْلَة وَلَيْلَة', 'كَلِيلَة وَدِمْنَة', 'مِئَة يَوْم', 'أَلْف يَوْم'], correct: 0,
    explain: 'أَلْف لَيْلَة وَلَيْلَة — so‘zma-so‘z «ming kecha va bir kecha».' },

  { id: 'w2d6s1', kind: 'Lug‘at', question: '🔴 «أَحْمَر» (ahmar) qaysi rang?',
    options: ['Ko‘k', 'Qizil', 'Sariq', 'Qora'], correct: 1,
    explain: 'أَحْمَر — qizil. Qora — أَسْوَد (aswad), oq — أَبْيَض (abyad).' },
  { id: 'w2d6s2', kind: 'Grammatika', question: '👥 «نَحْنُ» (nahnu) olmoshi nimani bildiradi?',
    options: ['Biz', 'Ular', 'Sizlar', 'Men'], correct: 0,
    explain: 'نَحْنُ — biz. Ular — هُمْ (hum).' },
  { id: 'w2d6s3', kind: 'Alifbo', question: '⭕ Harf ustidagi «ْ» (sukun) belgisi nimani bildiradi?',
    options: ['Harf ikki marta o‘qiladi', 'Harfdan keyin unli yo‘q', 'Cho‘ziq «a»', 'Harf o‘qilmaydi'], correct: 1,
    explain: 'Sukun — harf harakatsiz: مَكْتَب (mak-tab) dagi كْ ga unli qo‘shilmaydi.' },

  { id: 'w2d7s1', kind: 'Lug‘at', question: '🟢 «أَخْضَر» (axdar) qaysi rang?',
    options: ['Yashil', 'Qizil', 'Ko‘k', 'Oq'], correct: 0,
    explain: 'أَخْضَر — yashil. Ko‘k — أَزْرَق (azraq).' },
  { id: 'w2d7s2', kind: 'Raqamlar', question: '🔢 «أَرْبَعَة» (arba‘a) qaysi son?',
    options: ['3', '4', '5', '7'], correct: 1,
    explain: 'أَرْبَعَة — to‘rt (4). Uch — ثَلَاثَة, besh — خَمْسَة.' },
  { id: 'w2d7s3', kind: 'Viktorina', question: '🇺🇿 Qaysi o‘zbekcha so‘z arab tilidan kirgan?',
    options: ['Bola', 'Ilm', 'Qo‘l', 'Ot'], correct: 1,
    explain: '«Ilm» — arabcha عِلْم (‘ilm): bilim. Qolganlari turkiy so‘zlar.' },

  /* ---------- 3-hafta ---------- */
  { id: 'w3d1s1', kind: 'Lug‘at', question: '🎒 «طَالِب» (tālib) so‘zining ma’nosi?',
    options: ['O‘quvchi, talaba', 'Ustoz', 'Shifokor', 'Haydovchi'], correct: 0,
    explain: 'طَالِب — o‘quvchi/talaba (erkak), طَالِبَة — ayol.' },
  { id: 'w3d1s2', kind: 'Alifbo', question: '🔤 «ج» harfi qanday o‘qiladi?',
    options: ['X', 'J', 'H', 'Ch'], correct: 1,
    explain: 'ج — «jīm», J tovushi. Ostida bitta nuqta bor.' },
  { id: 'w3d1s3', kind: 'Viktorina', question: '🔠 Arab yozuvida bosh (katta) harflar bormi?',
    options: ['Ha, har gap boshida', 'Faqat ismlarda', 'Yo‘q, bosh harf yo‘q', 'Faqat sarlavhada'], correct: 2,
    explain: 'Arab yozuvida bosh harf yo‘q. Harflar so‘zdagi o‘rniga qarab shaklini o‘zgartiradi.' },

  { id: 'w3d2s1', kind: 'Lug‘at', question: '👨‍🏫 «مُعَلِّم» (mu‘allim) so‘zining ma’nosi?',
    options: ['O‘quvchi', 'Ustoz, o‘qituvchi', 'Direktor', 'Kitob'], correct: 1,
    explain: 'مُعَلِّم — o‘qituvchi. O‘zbekchadagi «muallim» shundan.' },
  { id: 'w3d2s2', kind: 'Grammatika', question: '👥 «أَنْتُمْ» (antum) nimani bildiradi?',
    options: ['Sizlar', 'Biz', 'Ular', 'Sen'], correct: 0,
    explain: 'أَنْتُمْ — sizlar (ko‘pchilikka murojaat).' },
  { id: 'w3d2s3', kind: 'Viktorina', question: '🌱 Arab tilidagi so‘zlar ko‘pincha necha harfli o‘zakdan yasaladi?',
    options: ['2 harfli', '3 harfli', '5 harfli', '7 harfli'], correct: 1,
    explain: 'Ko‘p so‘zlar 3 harfli o‘zakdan: ك ت ب → كَتَبَ (yozdi), كِتَاب (kitob), مَكْتَب (yozuv stoli).' },

  { id: 'w3d3s1', kind: 'Lug‘at', question: '🌸 «جَمِيل» (jamīl) so‘zining ma’nosi?',
    options: ['Chiroyli', 'Katta', 'Tez', 'Sovuq'], correct: 0,
    explain: 'جَمِيل — chiroyli (erkak jinsidagi so‘zga), جَمِيلَة — ayol jinsidagiga.' },
  { id: 'w3d3s2', kind: 'Grammatika', question: '👉 «هَذَا» (hāzā) qachon ishlatiladi?',
    options: ['«Bu» — erkak jinsidagi narsaga', '«U» — uzoqdagiga', '«Bular» — ko‘plikka', '«Qaysi?» — savolda'], correct: 0,
    explain: 'هَذَا كِتَاب — bu kitob. Ayol jinsidagiga — هَذِهِ (hāzihi).' },
  { id: 'w3d3s3', kind: 'Viktorina', question: '🧩 كَتَبَ (yozdi), كِتَاب (kitob), مَكْتَب (stol) — umumiy o‘zagi qaysi?',
    options: ['ك ت ب', 'م ك ت', 'ت ا ب', 'ك ا ت'], correct: 0,
    explain: 'O‘zak ك ت ب — «yozish» ma’nosi. Arab tilini o‘zak orqali o‘rganish so‘z boyligini tez oshiradi.' },

  { id: 'w3d4s1', kind: 'Lug‘at', question: '📅 «يَوْم» (yawm) so‘zining ma’nosi?',
    options: ['Kun', 'Oy', 'Yil', 'Soat'], correct: 0,
    explain: 'يَوْم — kun. Bugun — الْيَوْم (al-yawm).' },
  { id: 'w3d4s2', kind: 'Raqamlar', question: '🔢 «خَمْسَة» (xamsa) qaysi son?',
    options: ['5', '6', '8', '10'], correct: 0,
    explain: 'خَمْسَة — besh (5). Olti — سِتَّة (sitta).' },
  { id: 'w3d4s3', kind: 'Lug‘at', question: '📆 «السَّبْت» (as-sabt) haftaning qaysi kuni?',
    options: ['Dushanba', 'Chorshanba', 'Shanba', 'Yakshanba'], correct: 2,
    explain: 'السَّبْت — shanba. Yakshanba — الْأَحَد (al-ahad).' },

  { id: 'w3d5s1', kind: 'Lug‘at', question: '🌃 «لَيْل» (layl) so‘zining ma’nosi?',
    options: ['Tong', 'Tush', 'Tun', 'Kech'], correct: 2,
    explain: 'لَيْل — tun. Tong — صَبَاح (sabāh).' },
  { id: 'w3d5s2', kind: 'Ibora', question: '🌆 «مَسَاءُ الْخَيْر» (masā’u-l-xayr) nima degani?',
    options: ['Xayrli tong', 'Xayrli kech', 'Xayrli tun', 'Yoqimli ishtaha'], correct: 1,
    explain: 'مَسَاءُ الْخَيْر — xayrli kech. Javobi: مَسَاءُ النُّور.' },
  { id: 'w3d5s3', kind: 'Viktorina', question: '🍬 Inglizcha «sugar» (shakar) qaysi arabcha so‘zdan kelgan?',
    options: ['سُكَّر (sukkar)', 'عَسَل (‘asal)', 'مِلْح (milh)', 'خُبْز (xubz)'], correct: 0,
    explain: 'سُكَّر → lotincha «succarum» → «sugar». عَسَل — asal, مِلْح — tuz.' },

  { id: 'w3d6s1', kind: 'Lug‘at', question: '🐱 «قِطّ» (qitt) qaysi hayvon?',
    options: ['It', 'Mushuk', 'Ot', 'Qush'], correct: 1,
    explain: 'قِطّ — mushuk. Ot — حِصَان (hisān), qush — طَائِر (tā’ir).' },
  { id: 'w3d6s2', kind: 'Grammatika', question: '❓ «أَيْنَ؟» (ayna) savol so‘zi nimani so‘raydi?',
    options: ['Qachon?', 'Qayerda?', 'Nima uchun?', 'Kim?'], correct: 1,
    explain: 'أَيْنَ؟ — qayerda? Kim? — مَنْ؟, qachon? — مَتَى؟' },
  { id: 'w3d6s3', kind: 'Viktorina', question: '🌳 Arab tili qaysi til oilasiga kiradi?',
    options: ['Turkiy', 'Hind-yevropa', 'Som (semit)', 'Xitoy-tibet'], correct: 2,
    explain: 'Arab tili som (semit) tillari oilasiga kiradi — bu oiladagi eng ko‘p so‘zlashiladigan til.' },

  { id: 'w3d7s1', kind: 'Lug‘at', question: '🌊 «بَحْر» (bahr) so‘zining ma’nosi?',
    options: ['Daryo', 'Dengiz', 'Ko‘l', 'Tog‘'], correct: 1,
    explain: 'بَحْر — dengiz. Daryo — نَهْر (nahr), tog‘ — جَبَل (jabal).' },
  { id: 'w3d7s2', kind: 'Grammatika', question: '📐 «Katta uy» arabcha qanday tartibda aytiladi?',
    options: ['كَبِير بَيْت', 'بَيْت كَبِير', 'Ikkalasi bir xil', 'كَبِيرَة بَيْت'], correct: 1,
    explain: 'Arab tilida sifat otdan KEYIN keladi: بَيْت كَبِير — so‘zma-so‘z «uy katta».' },
  { id: 'w3d7s3', kind: 'Viktorina', question: '📜 Ibn Sino asarlarining ko‘pchiligi qaysi tilda yozilgan?',
    options: ['Fors', 'Arab', 'Turkiy', 'Lotin'], correct: 1,
    explain: 'Ibn Sinoning ko‘p asarlari, jumladan «Tib qonunlari», arab tilida yozilgan.' },

  /* ---------- 4-hafta ---------- */
  { id: 'w4d1s1', kind: 'Lug‘at', question: '🏙 «مَدِينَة» (madīna) so‘zining ma’nosi?',
    options: ['Qishloq', 'Shahar', 'Ko‘cha', 'Mamlakat'], correct: 1,
    explain: 'مَدِينَة — shahar. Mamlakat — بَلَد (balad).' },
  { id: 'w4d1s2', kind: 'Alifbo', question: '🔤 «د» harfi qanday o‘qiladi?',
    options: ['D', 'R', 'Z', 'V'], correct: 0,
    explain: 'د — «dāl», D tovushi. Bu harf keyingi harfga qo‘shilmaydi.' },
  { id: 'w4d1s3', kind: 'Viktorina', question: '🔢 Arabcha matnda ko‘p xonali sonlar qaysi yo‘nalishda o‘qiladi?',
    options: ['O‘ngdan chapga', 'Chapdan o‘ngga', 'Yuqoridan pastga', 'Farqi yo‘q'], correct: 1,
    explain: 'Matn o‘ngdan chapga yozilsa ham, sonlar chapdan o‘ngga o‘qiladi: 2026.' },

  { id: 'w4d2s1', kind: 'Lug‘at', question: '🛒 «سُوق» (sūq) so‘zining ma’nosi?',
    options: ['Bozor', 'Maktab', 'Uy', 'Bog‘'], correct: 0,
    explain: 'سُوق — bozor. Do‘kon — دُكَّان (dukkān), o‘zbekchadagi «do‘kon» shundan.' },
  { id: 'w4d2s2', kind: 'Ibora', question: '🙋 «مَا اسْمُكَ؟» (mā-smuka) nima degani?',
    options: ['Qayerdansiz?', 'Ismingiz nima?', 'Necha yoshdasiz?', 'Nima qilyapsiz?'], correct: 1,
    explain: 'مَا اسْمُكَ؟ — ismingiz nima? Javob: اِسْمِي … (ismī …) — ismim …' },
  { id: 'w4d2s3', kind: 'Viktorina', question: '0️⃣ Arabcha «صِفْر» (sifr) so‘zi nimani bildiradi?',
    options: ['Bir', 'Nol', 'O‘n', 'Yuz'], correct: 1,
    explain: 'صِفْر — nol. Yevropa tillaridagi «zero» va «cipher» so‘zlari shundan kelgan.' },

  { id: 'w4d3s1', kind: 'Lug‘at', question: '🍲 «طَعَام» (ta‘ām) so‘zining ma’nosi?',
    options: ['Ovqat', 'Suv', 'Choy', 'Meva'], correct: 0,
    explain: 'طَعَام — ovqat, taom. O‘zbekchadagi «taom» shundan.' },
  { id: 'w4d3s2', kind: 'Raqamlar', question: '🔢 «سِتَّة» (sitta) qaysi son?',
    options: ['6', '7', '8', '9'], correct: 0,
    explain: 'سِتَّة — olti (6). Yetti — سَبْعَة (sab‘a).' },
  { id: 'w4d3s3', kind: 'Viktorina', question: '💻 «Algoritm» so‘zi qaysi vatandoshimiz nomidan kelib chiqqan?',
    options: ['Beruniy', 'Al-Xorazmiy', 'Ibn Sino', 'Al-Farg‘oniy'], correct: 1,
    explain: 'Al-Xorazmiy nomi lotinchada «Algoritmi» deb yozilgan — «algoritm» shundan.' },

  { id: 'w4d4s1', kind: 'Lug‘at', question: '⚡ «سَرِيع» (sarī‘) so‘zining ma’nosi?',
    options: ['Sekin', 'Tez', 'Baland', 'Past'], correct: 1,
    explain: 'سَرِيع — tez. Sekin — بَطِيء (batī’).' },
  { id: 'w4d4s2', kind: 'Grammatika', question: '👉 «هَذِهِ» (hāzihi) qachon ishlatiladi?',
    options: ['«Bu» — ayol jinsidagi so‘zga', '«Bu» — erkak jinsidagiga', '«Ular» — ko‘plikka', '«U yer» — joyga'], correct: 0,
    explain: 'هَذِهِ سَيَّارَة — bu mashina (سَيَّارَة — muannas so‘z).' },
  { id: 'w4d4s3', kind: 'Grammatika', question: '✌️ Arab tilida «ikki» narsa uchun alohida shakl (ikkilik) bormi?',
    options: ['Yo‘q', 'Ha, alohida shakl bor', 'Faqat odamlar uchun', 'Faqat raqamlarda'], correct: 1,
    explain: 'Ha: كِتَاب — kitob, كِتَابَان — ikki kitob, كُتُب — kitoblar (3 va undan ko‘p).' },

  { id: 'w4d5s1', kind: 'Lug‘at', question: '❄️ «بَارِد» (bārid) so‘zining ma’nosi?',
    options: ['Issiq', 'Sovuq', 'Ho‘l', 'Quruq'], correct: 1,
    explain: 'بَارِد — sovuq. Issiq — حَارّ (hārr).' },
  { id: 'w4d5s2', kind: 'Lug‘at', question: '✅ Arabchada «ha» qanday aytiladi?',
    options: ['لَا (lā)', 'نَعَمْ (na‘am)', 'شُكْرًا (shukran)', 'مَرْحَبًا (marhaban)'], correct: 1,
    explain: 'نَعَمْ — ha, لَا — yo‘q, مَرْحَبًا — salom.' },
  { id: 'w4d5s3', kind: 'Viktorina', question: '🗺 Qaysi davlatda arab tili rasmiy til EMAS?',
    options: ['Misr', 'Marokash', 'Turkiya', 'Iroq'], correct: 2,
    explain: 'Turkiyaning rasmiy tili — turk tili. Misr, Marokash va Iroqda arab tili rasmiy.' },

  { id: 'w4d6s1', kind: 'Lug‘at', question: '🔥 «حَارّ» (hārr) so‘zining ma’nosi?',
    options: ['Sovuq', 'Issiq', 'Shirin', 'Achchiq'], correct: 1,
    explain: 'حَارّ — issiq (ob-havo yoki ovqat haqida).' },
  { id: 'w4d6s2', kind: 'Ibora', question: '🙌 «مَرْحَبًا» (marhaban) nima degani?',
    options: ['Xayr', 'Salom, xush kelibsiz', 'Kechirasiz', 'Rahmat'], correct: 1,
    explain: 'مَرْحَبًا — salom / xush kelibsiz. Javobi: مَرْحَبًا بِكَ.' },
  { id: 'w4d6s3', kind: 'Viktorina', question: '✍️ «Ma’no», «ta’lim» so‘zlaridagi tutuq belgisi (’) ko‘pincha qaysi arab harfi o‘rnida turadi?',
    options: ['ع (ayn)', 'ب (bā)', 'م (mīm)', 'س (sīn)'], correct: 0,
    explain: 'مَعْنَى (ma‘nā), تَعْلِيم (ta‘līm) — tutuq belgisi ع harfini bildiradi.' },

  { id: 'w4d7s1', kind: 'Lug‘at', question: '✨ «جَدِيد» (jadīd) so‘zining ma’nosi?',
    options: ['Eski', 'Yangi', 'Katta', 'Kichik'], correct: 1,
    explain: 'جَدِيد — yangi, قَدِيم (qadīm) — eski.' },
  { id: 'w4d7s2', kind: 'Raqamlar', question: '🔢 «سَبْعَة» (sab‘a) qaysi son?',
    options: ['5', '7', '9', '10'], correct: 1,
    explain: 'سَبْعَة — yetti (7). O‘n — عَشَرَة (‘ashara).' },
  { id: 'w4d7s3', kind: 'Viktorina', question: '🎓 Markazimiz nomidagi «Ta’lim» so‘zi arabchada nimani bildiradi?',
    options: ['O‘qitish, bilim berish', 'Sayohat', 'Savdo', 'Sport'], correct: 0,
    explain: 'تَعْلِيم (ta‘līm) — o‘qitish, bilim berish. «Hayot ta’limi» — hayot uchun bilim 🙂' }
];
